### PR TITLE
use TOML::Parser

### PR DESCRIPTION
**Pull request by karupanerura**
In my point of view, it's very difficult to maintain `TOML::from_toml` because -so far as I understand- there's some issues.
I created another parser implementation in order to solve problems.
If you think that is good, please use it.

https://metacpan.org/release/KARUPA/TOML-Parser-0.01

### CODE REVIEW

**Comment by dlc** [comment]
I like this, but I wonder if it makes sense to have both.  I'd be happy to give you the TOML namespace to own, as I've not been able to maintain it like I intended.

**Comment by karupanerura** [comment]
Thank you.
I undertake it with pleasure!

**Comment by dlc** [comment]
I've given go-maint status to KARUPA in PAUSE.

**Comment by karupanerura** [comment]
Maybe I've succeeded to release new TOML. (0.93)
https://metacpan.org/release/KARUPA/TOML-0.93

**Comment by dlc** [comment]
Looks good to me.  Thanks for taking this over.

**Pull request merged**
